/*
 * Licensed under the EUPL, Version 1.1 or – as soon they will be approved by
 * the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence. You may
 * obtain a copy of the Licence at:
 *
 * http://www.osor.eu/eupl/european-union-public-licence-eupl-v.1.1
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * Licence for the specific language governing permissions and limitations under
 * the Licence.
 */
package eu.stork.peps.auth.engine.core.validator.eidas;


import eu.stork.peps.auth.engine.core.eidas.EidasAttributesTypes;

import java.util.*;


public interface EIDASAttributes {

    String EIDAS10_NS = "urn:eu:stork:names:tc:STORK:1.0:assertion";
    String EIDAS10_PREFIX = "stork";
    String EIDASP10_NS = "urn:eu:stork:names:tc:STORK:1.0:protocol";
    String EIDASP10_PREFIX = "storkp";
    String TYPE_SUFFIX="Type";

    String ATTRIBUTE_NAME_PREFIX_NATURAL_PERSON = "http://eidas.europa.eu/attributes/naturalperson/";
    String ATTRIBUTE_NAME_PREFIX_LEGAL_PERSON = "http://eidas.europa.eu/attributes/legalperson/";

    String ATTRIBUTE_NAME_SUFFIX_GIVENNAME = "CurrentFamilyName";
    String ATTRIBUTE_GIVENNAME = ATTRIBUTE_NAME_PREFIX_NATURAL_PERSON + ATTRIBUTE_NAME_SUFFIX_GIVENNAME;

    String ATTRIBUTE_NAME_SUFFIX_FIRSTNAME = "CurrentGivenName";
    String ATTRIBUTE_FIRSTNAME = ATTRIBUTE_NAME_PREFIX_NATURAL_PERSON + ATTRIBUTE_NAME_SUFFIX_FIRSTNAME;

    String ATTRIBUTE_NAME_SUFFIX_DATEOFBIRTH = "DateOfBirth";
    String ATTRIBUTE_DATEOFBIRTH = ATTRIBUTE_NAME_PREFIX_NATURAL_PERSON + ATTRIBUTE_NAME_SUFFIX_DATEOFBIRTH;

    String ATTRIBUTE_NAME_SUFFIX_PERSONIDENTIFIER = "PersonIdentifier";
    String ATTRIBUTE_PERSONIDENTIFIER = ATTRIBUTE_NAME_PREFIX_NATURAL_PERSON + ATTRIBUTE_NAME_SUFFIX_PERSONIDENTIFIER;

    String ATTRIBUTE_NAME_SUFFIX_BIRTHNAME = "BirthName";
    String ATTRIBUTE_BIRTHNAME = ATTRIBUTE_NAME_PREFIX_NATURAL_PERSON + ATTRIBUTE_NAME_SUFFIX_BIRTHNAME;

    String ATTRIBUTE_NAME_SUFFIX_CURRENTADDRESS = "CurrentAddress";
    String ATTRIBUTE_CURRENTADDRESS = ATTRIBUTE_NAME_PREFIX_NATURAL_PERSON + ATTRIBUTE_NAME_SUFFIX_CURRENTADDRESS;

    String ATTRIBUTE_NAME_SUFFIX_PLACEOFBIRTH = "PlaceOfBirth";
    String ATTRIBUTE_PLACEOFBIRTH = ATTRIBUTE_NAME_PREFIX_NATURAL_PERSON + ATTRIBUTE_NAME_SUFFIX_PLACEOFBIRTH;

    String ATTRIBUTE_NAME_SUFFIX_GENDER = "Gender";
    String ATTRIBUTE_GENDER = ATTRIBUTE_NAME_PREFIX_NATURAL_PERSON + ATTRIBUTE_NAME_SUFFIX_GENDER;

    String ATTRIBUTE_NAME_SUFFIX_LEGALIDENTIFIER = "LegalPersonIdentifier";
    String ATTRIBUTE_LEGALIDENTIFIER = ATTRIBUTE_NAME_PREFIX_LEGAL_PERSON + ATTRIBUTE_NAME_SUFFIX_LEGALIDENTIFIER;

    String ATTRIBUTE_NAME_SUFFIX_LEGALADDRESS = "LegalAddress";
    String ATTRIBUTE_LEGALADDRESS = ATTRIBUTE_NAME_PREFIX_LEGAL_PERSON + ATTRIBUTE_NAME_SUFFIX_LEGALADDRESS;

    String ATTRIBUTE_NAME_SUFFIX_LEGALNAME = "LegalName";
    String ATTRIBUTE_LEGALNAME = ATTRIBUTE_NAME_PREFIX_LEGAL_PERSON + ATTRIBUTE_NAME_SUFFIX_LEGALNAME;

    String ATTRIBUTE_NAME_SUFFIX_VATREGISTRATION = "VATRegistration";
    String ATTRIBUTE_VATREGISTRATION = ATTRIBUTE_NAME_PREFIX_LEGAL_PERSON + ATTRIBUTE_NAME_SUFFIX_VATREGISTRATION;

    String ATTRIBUTE_NAME_SUFFIX_TAXREFERENCE = "TaxReference";
    String ATTRIBUTE_TAXREFERENCE = ATTRIBUTE_NAME_PREFIX_LEGAL_PERSON + ATTRIBUTE_NAME_SUFFIX_TAXREFERENCE;

    String ATTRIBUTE_NAME_SUFFIX_BUSINESSCODE = "D-2012-17-EUIdentifier";
    String ATTRIBUTE_BUSINESSCODE = ATTRIBUTE_NAME_PREFIX_LEGAL_PERSON + ATTRIBUTE_NAME_SUFFIX_BUSINESSCODE;

    String ATTRIBUTE_NAME_SUFFIX_LEI = "LEI";
    String ATTRIBUTE_LEI = ATTRIBUTE_NAME_PREFIX_LEGAL_PERSON + ATTRIBUTE_NAME_SUFFIX_LEI;

    String ATTRIBUTE_NAME_SUFFIX_EORI = "EORI";
    String ATTRIBUTE_EORI = ATTRIBUTE_NAME_PREFIX_LEGAL_PERSON + ATTRIBUTE_NAME_SUFFIX_EORI;

    String ATTRIBUTE_NAME_SUFFIX_SEED = "SEED";
    String ATTRIBUTE_SEED = ATTRIBUTE_NAME_PREFIX_LEGAL_PERSON + ATTRIBUTE_NAME_SUFFIX_SEED;

    String ATTRIBUTE_NAME_SUFFIX_SIC = "SIC";
    String ATTRIBUTE_SIC = ATTRIBUTE_NAME_PREFIX_LEGAL_PERSON + ATTRIBUTE_NAME_SUFFIX_SIC;




    Map<String, EidasAttributesTypes> ATTRIBUTES_SET = Collections.unmodifiableMap(
            new HashMap<String, EidasAttributesTypes>(){
                {
                    put(ATTRIBUTE_GIVENNAME, EidasAttributesTypes.NATURAL_PERSON_MANDATORY);
                    put(ATTRIBUTE_FIRSTNAME, EidasAttributesTypes.NATURAL_PERSON_MANDATORY);
                    put(ATTRIBUTE_DATEOFBIRTH, EidasAttributesTypes.NATURAL_PERSON_OPTIONAL);
                    put(ATTRIBUTE_PERSONIDENTIFIER, EidasAttributesTypes.NATURAL_PERSON_MANDATORY);
                    put(ATTRIBUTE_BIRTHNAME, EidasAttributesTypes.NATURAL_PERSON_OPTIONAL);
                    put(ATTRIBUTE_CURRENTADDRESS, EidasAttributesTypes.NATURAL_PERSON_OPTIONAL);
                    put(ATTRIBUTE_PLACEOFBIRTH, EidasAttributesTypes.NATURAL_PERSON_OPTIONAL);
                    put(ATTRIBUTE_GENDER, EidasAttributesTypes.NATURAL_PERSON_OPTIONAL);
                    put(ATTRIBUTE_LEGALIDENTIFIER, EidasAttributesTypes.LEGAL_PERSON_MANDATORY);
                    put(ATTRIBUTE_LEGALADDRESS, EidasAttributesTypes.LEGAL_PERSON_OPTIONAL);
                    put(ATTRIBUTE_LEGALNAME, EidasAttributesTypes.LEGAL_PERSON_MANDATORY);
                    put(ATTRIBUTE_VATREGISTRATION, EidasAttributesTypes.LEGAL_PERSON_OPTIONAL);
                    put(ATTRIBUTE_TAXREFERENCE, EidasAttributesTypes.LEGAL_PERSON_OPTIONAL);
                    put(ATTRIBUTE_BUSINESSCODE, EidasAttributesTypes.LEGAL_PERSON_OPTIONAL);
                    put(ATTRIBUTE_LEI, EidasAttributesTypes.LEGAL_PERSON_OPTIONAL);
                    put(ATTRIBUTE_EORI, EidasAttributesTypes.LEGAL_PERSON_OPTIONAL);
                    put(ATTRIBUTE_SEED, EidasAttributesTypes.LEGAL_PERSON_OPTIONAL);
                    put(ATTRIBUTE_SIC, EidasAttributesTypes.LEGAL_PERSON_OPTIONAL);
                }
            }
    );
    Map<String, String> ATTRIBUTES_SET_NAMES = Collections.unmodifiableMap(
            new HashMap<String, String>(){
                {
                    put(ATTRIBUTE_GIVENNAME, ATTRIBUTE_NAME_SUFFIX_GIVENNAME);
                    put(ATTRIBUTE_FIRSTNAME, ATTRIBUTE_NAME_SUFFIX_FIRSTNAME);
                    put(ATTRIBUTE_DATEOFBIRTH, ATTRIBUTE_NAME_SUFFIX_DATEOFBIRTH);
                    put(ATTRIBUTE_PERSONIDENTIFIER, ATTRIBUTE_NAME_SUFFIX_PERSONIDENTIFIER);
                    put(ATTRIBUTE_BIRTHNAME, ATTRIBUTE_NAME_SUFFIX_BIRTHNAME);
                    put(ATTRIBUTE_CURRENTADDRESS, ATTRIBUTE_NAME_SUFFIX_CURRENTADDRESS);
                    put(ATTRIBUTE_PLACEOFBIRTH, ATTRIBUTE_NAME_SUFFIX_PLACEOFBIRTH);
                    put(ATTRIBUTE_GENDER, ATTRIBUTE_NAME_SUFFIX_GENDER);
                    put(ATTRIBUTE_LEGALIDENTIFIER, ATTRIBUTE_NAME_SUFFIX_LEGALIDENTIFIER);
                    put(ATTRIBUTE_LEGALADDRESS, ATTRIBUTE_NAME_SUFFIX_LEGALADDRESS);
                    put(ATTRIBUTE_LEGALNAME, ATTRIBUTE_NAME_SUFFIX_LEGALNAME);
                    put(ATTRIBUTE_VATREGISTRATION,ATTRIBUTE_NAME_SUFFIX_VATREGISTRATION );
                    put(ATTRIBUTE_TAXREFERENCE, ATTRIBUTE_NAME_SUFFIX_TAXREFERENCE);
                    put(ATTRIBUTE_BUSINESSCODE, ATTRIBUTE_NAME_SUFFIX_BUSINESSCODE);
                    put(ATTRIBUTE_LEI, ATTRIBUTE_NAME_SUFFIX_LEI);
                    put(ATTRIBUTE_EORI, ATTRIBUTE_NAME_SUFFIX_EORI);
                    put(ATTRIBUTE_SEED, ATTRIBUTE_NAME_SUFFIX_SEED);
                    put(ATTRIBUTE_SIC, ATTRIBUTE_NAME_SUFFIX_SIC);
                }
            }
    );
    Map<String, String> ATTRIBUTES_SET_TYPES = Collections.unmodifiableMap(
            new HashMap<String, String>(){
                {
                    put(ATTRIBUTE_GIVENNAME, ATTRIBUTE_NAME_SUFFIX_GIVENNAME+TYPE_SUFFIX);
                    put(ATTRIBUTE_FIRSTNAME, ATTRIBUTE_NAME_SUFFIX_FIRSTNAME+TYPE_SUFFIX);
                    put(ATTRIBUTE_DATEOFBIRTH, ATTRIBUTE_NAME_SUFFIX_DATEOFBIRTH+TYPE_SUFFIX);
                    put(ATTRIBUTE_PERSONIDENTIFIER, ATTRIBUTE_NAME_SUFFIX_PERSONIDENTIFIER+TYPE_SUFFIX);
                    put(ATTRIBUTE_BIRTHNAME, ATTRIBUTE_NAME_SUFFIX_BIRTHNAME+TYPE_SUFFIX);
                    put(ATTRIBUTE_CURRENTADDRESS, ATTRIBUTE_NAME_SUFFIX_CURRENTADDRESS+TYPE_SUFFIX);
                    put(ATTRIBUTE_PLACEOFBIRTH, ATTRIBUTE_NAME_SUFFIX_PLACEOFBIRTH+TYPE_SUFFIX);
                    put(ATTRIBUTE_GENDER, ATTRIBUTE_NAME_SUFFIX_GENDER+TYPE_SUFFIX);
                    put(ATTRIBUTE_LEGALIDENTIFIER, ATTRIBUTE_NAME_SUFFIX_LEGALIDENTIFIER+TYPE_SUFFIX);
                    put(ATTRIBUTE_LEGALADDRESS, "LegalPersonAddressType");
                    put(ATTRIBUTE_LEGALNAME, ATTRIBUTE_NAME_SUFFIX_LEGALNAME+TYPE_SUFFIX);
                    put(ATTRIBUTE_VATREGISTRATION,"VATRegistrationNumberType" );
                    put(ATTRIBUTE_TAXREFERENCE, ATTRIBUTE_NAME_SUFFIX_TAXREFERENCE+TYPE_SUFFIX);
                    put(ATTRIBUTE_BUSINESSCODE, ATTRIBUTE_NAME_SUFFIX_BUSINESSCODE+TYPE_SUFFIX);
                    put(ATTRIBUTE_LEI, ATTRIBUTE_NAME_SUFFIX_LEI+TYPE_SUFFIX);
                    put(ATTRIBUTE_EORI, ATTRIBUTE_NAME_SUFFIX_EORI+TYPE_SUFFIX);
                    put(ATTRIBUTE_SEED, ATTRIBUTE_NAME_SUFFIX_SEED+TYPE_SUFFIX);
                    put(ATTRIBUTE_SIC, ATTRIBUTE_NAME_SUFFIX_SIC+TYPE_SUFFIX);
                }
            }
    );
}
