<%@ page contentType="text/html; charset=UTF-8" %>
<%@ taglib prefix="s" uri="/struts-tags" %>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <meta http-equiv='pragma' content='no-cache'/>
    <meta http-equiv='cache-control' content='no-cache, no-store, must-revalidate'/>
	<meta http-equiv="Expires" content="-1"/>
    <title><s:property value="%{getText('tituloId')}"/></title>
    <script type="text/javascript" src="js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="js/script.js"></script>
    <script type="text/javascript" src="js/base64.js"></script>
    <link href="css/estilos.css" rel="stylesheet" type="text/css"/>
</head>
<body>


<div id="contenedor">
    <div id="cabecera">
        <div class="logo"></div>
        <div class="tituloCabecera"><s:property value="%{getText('tituloCabeceraId')}"/></div>
    </div>
    <div id="borde">
        <div id="principal">
            <div id="margen">

                <h1><s:property value="%{providerName}"/></h1>
                <h2>SamlRequest generated by the SP</h2>
                <div id="space"></div>



                <table border="0" cellpadding="1" cellspacing="1" class="borde" width="100%">
                    <tr>
                    <form id="countrySelector" name="countrySelector" action="<s:property value="pepsUrl" />" target="_parent" onsubmit="setSAMRequestMethod();">
                            <td width="20%" class="tdLabel">
                                <s:property value="%{getText('destinationCountryId')}"/></td>
                            <td><input type="text" name="country" value="<s:property value="citizen"/>" id="input"/></td>
                    </tr>
                    <tr><td class="tdLabel">
                        <s:property value="%{getText('SAMLRequestId')}"/></td>
                        <td><textarea name="SAMLRequest" cols="80" rows="5"><s:property value="SAMLRequest"/></textarea></td>
                    </tr>
                    <tr><td colspan=2>
                        <div id="botones">
							<div class="radiobuttons">
                                <input type="radio" name="sendmethods" id="postmethod" value="POST" checked onChange="ajaxChangeHttpMethod('samlRequestXML','changeProtocolBinding.action', receiveSignedRequest,errorAjaxRequest)"/><label for="postmethod">HTTP Post Binding</label><br/>
                                <input type="radio" name="sendmethods" id="getmethod" value="GET" onChange="ajaxChangeHttpMethod('samlRequestXML','changeProtocolBinding.action', receiveSignedRequest,errorAjaxRequest)"/><label for="getmethod">HTTP Redirect Binding</label>
							</div> 
							<br/>
                            <input type="submit" value="Submit"/>
						</div>
						<div id="space"></div>
                    </form>
					<br/>
                    <form id="samlRequestXML" name="samlRequestXML" action="reSign">
                        <input type="hidden" id="samlRequestBinding" name="samlRequestBinding" value="POST">
                        <div id="botones">
                            <input id="encodeButton" name="encodeButton" type="button" value="Re-sign and Encode" OnClick=signAndEncodeSAMLRequest(); />
                            <input type="button" value="Decode" OnClick=decodeSAMLRequest(); />
                        </div>
                        <div id="space"></div>
                    </td></tr>
                    <tr><td class="tdLabel">
                        <s:property value="%{getText('SAMLRequestXMLId')}"/></td>
                        <td><textarea name="samlRequestXML" cols="80" rows="20"><s:property value="samlRequestXML"/></textarea>
                        </td></tr>
                    </form>
                </table>

            </div>
        </div>
    </div>
</div>
</body>
</html>
